"""Payment Types relation

Revision ID: 55d42624a791
Revises: 72e39320d5ea
Create Date: 2021-04-12 17:56:28.811543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55d42624a791'
down_revision = '72e39320d5ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('paymenttype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'customers', 'payment_methods', ['paymenttype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_column('customers', 'paymenttype_id')
    # ### end Alembic commands ###
