"""Relationship

Revision ID: 72e39320d5ea
Revises: b9565384a7fb
Create Date: 2021-04-12 17:51:07.546779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72e39320d5ea'
down_revision = 'b9565384a7fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('producttype_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'product_types', ['producttype_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'producttype_id')
    # ### end Alembic commands ###
